% Auto-generated by cameraCalibrator app on 13-Aug-2019
%-------------------------------------------------------


% Define images to process
imageFileNames = {'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_46_52.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_46_57.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_47_04.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_47_17.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_47_21.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_47_24.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_47_33.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_47_36.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_48_11.jpg',...
    'D:\Kevinly Santoso\Documents\UNI\y4s2\MTRN4230\Assignments\Assignment 2\Conveyor_Calibration\conveyor__08_07_18_48_17.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParamsConveyor, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
%h1=figure; showReprojectionErrors(cameraParamsConveyor);

% Visualize pattern locations
%h2=figure; showExtrinsics(cameraParamsConveyor, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParamsConveyor);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParamsConveyor);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
